import org.gradle.jvm.tasks.Jar

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.fml.loom)
    alias(libs.plugins.quick)
    `maven-publish`
}

val mod_name: String by project
val mod_version: String by project
val mod_id: String by project

// JitPack cannot recognize tags like 1.1.3+kotlin.2.3.10,
// so here we use sub-version numbers like 2310 instead.
val kv = libs.versions.kotlin.get()
    .split(".")
    .map { it.toInt() }
    // 2.10.10 or 2.1.100 ?
    .zip(listOf(1000, 100, 1))
    .sumOf { (k, v) -> k * v }

version = "$mod_version.$kv"

base {
    archivesName = mod_id
}

repositories {
    maven("https://jitpack.io")
    maven("https://maven.limingzxc.top/repository/maven-public/")
}

val loader: Configuration by configurations.creating {
    configurations.implementation.get().extendsFrom(this)
}

val sources: Configuration by configurations.creating

dependencies {
    minecraft("Minecraft:IsTooEasy:1.6.4-MITE")

    // Add fish mod loader dependency
    loader( "com.github.MinecraftIsTooEasy:FishModLoader:3.4.2")

    pkg(libs.kotlin.stdlib)
    pkg(libs.kotlin.reflect)
    pkg(libs.kotlinx.coroutines)

    sources(libs.kotlin.stdlib) {
        artifact {
            classifier = "sources"
        }
    }

    sources(libs.kotlin.reflect) {
        artifact {
            classifier = "sources"
        }
    }

    sources(libs.kotlinx.coroutines) {
        artifact {
            classifier = "sources"
        }
    }

}

loom {
    mergedMinecraftJar()

    fml = loader.files.first()

    // Add the mappings generated by FML to the mappings configuration
    project.dependencies.add("mappings", fmlMCPMappings())

    mods {
        create(mod_name) {
            sourceSet(sourceSets.main.get())
        }
    }
}


tasks.processResources {
    inputs.property("version", project.version)

    filesMatching("fml.mod.json") {
        expand("version" to project.version)
    }
}

java {
    withSourcesJar()
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}


tasks.named<Jar>("sourcesJar") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(sources.map { zipTree(it) })
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
        }
    }
}
